### ISSUE TITLE
Help Wanted: Using Russh to execute multiple commands

### ISSUE THREAD

**Issue by mTsBucy1** [warp-tech/russh#109]
For https://github.com/mTsBucy1/async-ssh2-tokio-fork I would like to be able to sequentially execute many commands on the same host (See also https://github.com/Miyoshi-Ryota/async-ssh2-tokio/issues/12).

Currently we create one Handler Implementation and call `connect` to get a Session Handle and authenticate this.
We then call `channel_open_session()` and `channel.exec` for every command that needs execution.
This was done, because calling `channel.exec` multiple times has failed.

However, after exactly 10 invocations, the session gets disconnected (presumably by the server). This was demonstrated on a Windows OpenSSH server and a Ubuntu ssh server.

I've tried looking into the russh code to understand the issue, but without success. The one thing I tried, was to override `Handler::channel_close` to also send a `session.close(channel);` packet back to the server. This was unsuccessful, but I also found no reference of a channel ever getting closed any other way.

Is this an inherit limitation of the session and do we need to reconnect and/or reauthenticate every 10 invocations? Or is there something we missed?
If someone with more SSH knowledge could point me in the right direction that would be amazing.
If you need a minimal reproducable example or further explanations from my side, please ask, but I maybe someone here knows of a approach to solve this.

**Comment by Eugeny** [comment]
This is actually expected. You can't execute multiple commands on a single channel, and in most distros, OpenSSH server config limits the max number of channels, both simultaneous and total. Make sure that you're closing channels after the command is complete so that you're not hitting the lower simultaneous channel limit

**Comment by mTsBucy1** [comment]
Thanks for your answer @Eugeny, I was just wondering how I can close the channel manually. I couldn't find any function in the documentation, neither on the Handle nor on the Channel. As stated, I tried to override `Handler::channel_close` to send a Close message back, because I definitely get a Close message from the server, but firstly, it didn't increase the limit, and secondly, I now have a memory leak, because I can't remove the channel from the private HashMap holding the channels in the Session.

And just to clarify, the ssh connection will regularly have to be reconnected (or only re-authenticated?) every once in a while?

**Comment by Eugeny** [comment]
You're correct! For some reason there is no `Channel` method to close it yet - so channels currently can only be closed via [Session::close](https://docs.rs/russh/0.35.0-beta.9/russh/client/struct.Session.html#method.close)

**Comment by Eugeny** [comment]
Should be fixed now.

**Comment by mTsBucy1** [comment]
Thanks for the quick fix 🚀

**Comment by yorkz1994** [comment]
> Should be fixed now.

I tried new in version 0.36.0, but it seems still not working.
I modified the remote_shell_call.rs to run 11 times of the call, no matter I close the channel or not, the 11th call will always fail.

<code>
...
Result10: root

11
[2023-01-31T09:03:33Z DEBUG russh::cipher] writing, seqn = 26
[2023-01-31T09:03:33Z DEBUG russh::cipher] padding length 7
[2023-01-31T09:03:33Z DEBUG russh::cipher] packet_length 32
[2023-01-31T09:03:33Z DEBUG russh::cipher] reading, len = [80, 109, 197, 9]
[2023-01-31T09:03:33Z DEBUG russh::cipher] reading, seqn = 80
[2023-01-31T09:03:33Z DEBUG russh::cipher] reading, clear len = 56
[2023-01-31T09:03:33Z DEBUG russh::cipher] read_exact 60
[2023-01-31T09:03:33Z DEBUG russh::cipher] read_exact done
[2023-01-31T09:03:33Z DEBUG russh::cipher] reading, padding_length 11
[2023-01-31T09:03:33Z DEBUG russh::client::encrypted] channel_open_failure
[2023-01-31T09:03:33Z DEBUG russh::client] drop handle
[2023-01-31T09:03:33Z DEBUG russh::client] disconnected
[2023-01-31T09:03:33Z DEBUG russh::client] drop session
Error: Failed to open channel (ConnectFailed)
</code>
[remote_shell_call.zip](https://github.com/warp-tech/russh/files/10544616/remote_shell_call.zip)

The modified example file attached.

**Comment by mTsBucy1** [comment]
@yorkz1994 Indeed there is a setting in the OpenSSH server called **MaxSessions** (see `man 5 sshd_config` on unix) that limits the number of channels, no matter whether opened or closed.

The workaround is to either use a shell or open new connections and reauthenticate (we chose the latter option for the [async-ssh2-tokio crate](https://github.com/Miyoshi-Ryota/async-ssh2-tokio)).

Hope this helps

**Comment by yorkz1994** [comment]
@mTsBucy1 Thank you for this, but the setting should be for max parallel sessions, if you close a channel, then it can be reused.
I tried to use golang SSH library, there is no such problem.
I found a bug that caused channel leak and create a PR. It got merged today.
https://github.com/warp-tech/russh/pull/119#issue-1565684413
